# Install and cache node.
language: node_js
os: linux
node_js: 
  - "8"
  # - "9"
  - "10"
  # - "11"
  - "12"

# Job Pipeline
jobs:
  include:
    - stage: "unit testing"
      script: npm run test
    - stage: "master branch coverage"                 
      if: branch IN (master)
      script: npm run coverall
    - stage: "npm release"
      if: (tag IS present) and (branch IN (master))
      before_deploy:
      - npm run build
      - npm run bundle
      deploy:
        provider: npm
        edge: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          skip_cleanup: true
